// <auto-generated />
using System;
using BrightApp.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrightApp.Server.Migrations
{
    [DbContext(typeof(BleetContext))]
    partial class BleetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BrightApp.Shared.Bleet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BleetText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BleetTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bleets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BleetText = "Que sera sera",
                            BleetTitle = "First Bleet",
                            CreatedAt = new DateTime(2022, 9, 27, 11, 36, 21, 61, DateTimeKind.Local).AddTicks(8147),
                            CreatorUsername = "@stephen_krogger"
                        },
                        new
                        {
                            Id = 2,
                            BleetText = "And so the robots spared humanity",
                            BleetTitle = "The doom of mankind",
                            CreatedAt = new DateTime(2022, 9, 27, 11, 36, 21, 61, DateTimeKind.Local).AddTicks(8158),
                            CreatorUsername = "@elon_musk"
                        },
                        new
                        {
                            Id = 3,
                            BleetText = "My Model X is the greatest thing I have ever purchased. Period.",
                            BleetTitle = "Sometime in the future...",
                            CreatedAt = new DateTime(2022, 9, 27, 11, 36, 21, 61, DateTimeKind.Local).AddTicks(8160),
                            CreatorUsername = "@stephen_krogger"
                        },
                        new
                        {
                            Id = 4,
                            BleetText = "It cost me everything to balance the world but, the Avengers thwarted my plan by going back in time and killing me. Gamora these are my last words for you, Avenge me!!!",
                            BleetTitle = "Avenge me, Gamora!",
                            CreatedAt = new DateTime(2022, 9, 27, 11, 36, 21, 61, DateTimeKind.Local).AddTicks(8161),
                            CreatorUsername = "@probably_thanos"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
